export enum ProductActions {
    GET_LIST_REQUEST = '@beers/GET_LIST_REQUEST',
    GET_LIST_SUCCESS = '@beers/GET_LIST_SUCCESS',
    GET_LIST_FAILURE = '@beers/GET_LIST_FAILURE',

    NEW_PRODUCT_REQUEST = '@beers/NEW_PRODUCT_REQUEST',
    NEW_PRODUCT_SUCCESS = '@beers/NEW_PRODUCT_SUCCESS',
    NEW_PRODUCT_FAILURE = '@beers/NEW_PRODUCT_FAILURE',

    DELETE_PRODUCT_REQUEST = '@beers/DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS = '@beers/DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE = '@beers/DELETE_PRODUCT_FAILURE',
}